export const instruments = [
  { symbol: "IBM", name: "INTERNATIONAL BUS MACH CORP" },
  { symbol: "A", name: "AGILENT TECHNOLOGIES INC" },
  { symbol: "AA", name: "ALCOA CORPORATION" },
  { symbol: "AACG", name: "ATA CREATIVITY GLOBAL SPON ADS EACH REP 2 ORD SHS" },
  { symbol: "AAL", name: "AMERICAN AIRLINES GROUP INC" },
  { symbol: "AAMC", name: "ALTISOURCE ASSET MANAGEMENT CORP" },
  { symbol: "AAME", name: "ATLANTIC AMERICAN CORP" },
  { symbol: "AAN", name: "AARONS INC" },
  { symbol: "AAOI", name: "APPLIED OPTOELECTRONICS INC" },
  { symbol: "AAON", name: "AAON INC" },
  { symbol: "AAP", name: "ADVANCE AUTO PARTS INC" },
  { symbol: "AAPL", name: "APPLE INC" },
  { symbol: "AAT", name: "AMERICAN ASSETS TRUST INC" },
  { symbol: "AAU", name: "ALMADEN MINERALS LTD" },
  { symbol: "AAWW", name: "ATLAS AIR WORLDWIDE HOLDINGS INC" },
  { symbol: "AAXN", name: "AXON ENTERPRISE INC" },
  { symbol: "AB", name: "ALLIANCEBERNSTEIN HOLDING LP" },
  { symbol: "ABB", name: "ABB LTD SPON ADR EACH REP 1 ORD SHS" },
  { symbol: "ABBV", name: "ABBVIE INC" },
  { symbol: "ABC", name: "AMERISOURCEBERGEN CORPORATION" },
  { symbol: "ABCB", name: "AMERIS BANCORP" },
];
